[utils]
label = "Utilities"
pacman = [
  "btop",
  "cava",
  "brightnessctl",
  "bc",
  "jq",
  "imagemagick",
  "chafa",
  "xdg-user-dirs",
  "yad",
  "rofi",
  "xdotool",
  "rsync",
  "wget",
  "unzip",
  "pacman-contrib",
  "qalculate-gtk",
  "nvtop",
  "yt-dlp",
  "baobab",
  "inxi",
  "7zip",
  "power-profiles-daemon",
]
aur = [
  "octopi",
]

[sync]
label = "Cloud Sync"
aur = [
  "onedrive-abraunegg",
]

[self-hosted]
label = "Self-hosted & VPN"
pacman = [
  "tailscale",
  "sunshine",
]

[apps]
label = "Applications"
pacman = [
  "obsidian",
  "remmina",
  "freerdp",
  "vlc",
  "loupe",
]
aur = [
  "vesktop-bin",
  "zen-browser-bin",
  "onlyoffice-bin",
]

[neovim]
label = "Neovim Editor"
pacman = [
  "lazygit",
  "neovim",
  "tree-sitter-cli",
]

[quickshell]
label = "Quickshell"
aur = [
  "quickshell-overview-git",
]
